FORMAT: 1A
HOST: http://darwin.hacktrain.com/

# Darwin REST API

This page contains the documentation for Darwin's REST API. This is an open source project initiated and led by the [HackTrain team](http://hacktrain.com). If you are interested on contributing, feel free to [fork the repo on github](https://github.com/HackPartners/darwinrest), or drop us a line at [hello@hackpartners.com](mailito:hello@hackpartners.com).
<br>
<br>

The Darwin REST API consists of a few core endpoints that can be queried through a GET request. You can test most of these examples by just copying the links and opening them in your web browser. Some example endpoints you can try out of the box are:

* [http://darwin.hacktrain.com/api/crs](http://darwin.hacktrain.com/api/crs)
* [http://darwin.hacktrain.com/api/status](http://darwin.hacktrain.com/api/status)

For other requests, you will be required to register at the [National Rail Enquiries](http://www.nationalrail.co.uk/46391.aspx) to obtain your Darwin OpenLDWS API Key.

# Group ./status

## ./status [/api/status]

### /status [GET]

+ Response 200 (application/json)

        {
            "OpenLDBWS": "Available"
        }

# Group ./station

## ./station/code/{query} [/api/station/code/{query}]

Retreive either all station CRS codes, or a subset of codes

+ Parameters
    + query (string, optional, `eu`)

        The query to filter station names with

### /station/code/eu  [GET]

+ Response 200 (application/json)

        {
            "ASI": "Ashford International (Eurostar)", 
            "BEU": "Beaulieu Road", 
            "EBA": "Euxton Balshaw Lane", 
            "EUS": "London Euston", 
            "LEU": "Leuchars (for St. Andrews)", 
            "PRH": "Penrhyndeudraeth"
        }
            
## ./station/detail/{query} [/api/station/detail/{query}]
Retreive metadata about the stations, including location, sttaion code, etc.

+ Parameters
    + query (string, optional, `EUS`)

        The query to filter station names with

### /station/detail/eus  [GET]

+ Response 200 (application/json)

        [
          {
            "crs": "EUS",
            "owner": "Network Rail",
            "postcode": "NW1 2RT, UK",
            "stationName": "Euston"
          }
        ] 

# Group ./train

## ./train/{station} [/api/train/{station}?apiKey={apiKey}&rows={rows}]

Retreive all departures and arrivals for the station given, which can be either a station code, or a station name.

+ Parameters
    + station (string, `Eus`)  
        The name or code for the station
    + apiKey (string, `b55bbec8-81d3-4ba5-8626-c1c7568a8106`) 
        The Darwin API key
    + rows (int, optional) 
        The number of rows to return (up to 150)
        + Default: 10
        

### /train/EUS [GET]

+ Response 200 (application/json)

        [
            {
                "destinations": [
                    {
                        "stationCode": "GLC", 
                        "stationName": "Glasgow Central"
                    }, 
                    {
                        "stationCode": "EDB", 
                        "stationName": "Edinburgh"
                    }
                ], 
                "estimatedArrivalTime": null, 
                "estimatedDepartureTime": "On time", 
                "operatorCode": "CS", 
                "operatorName": "Caledonian Sleeper", 
                "origins": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "platform": "1", 
                "scheduledArrivalTime": null, 
                "scheduledDepartureTime": "23:50", 
                "serviceId": "2MTvBgDvOM22s56FAz1kLA=="
            }, 
            {
                "destinations": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "estimatedArrivalTime": "23:44", 
                "estimatedDepartureTime": null, 
                "operatorCode": "VT", 
                "operatorName": "Virgin Trains", 
                "origins": [
                    {
                        "stationCode": "MAN", 
                        "stationName": "Manchester Piccadilly"
                    }
                ], 
                "platform": "3", 
                "scheduledArrivalTime": "23:51", 
                "scheduledDepartureTime": null, 
                "serviceId": "sB98KMHDSLteYxb1lLMxmg=="
            }
        ]
        

## ./train/{station}/to [/api/train/{station}/to?apiKey={apiKey}&rows={rows}]
Retreive all departures for the station given, which can be either a station code, or a station name.

+ Parameters
    + station (string, `EUS`)  
        The name or code for the station
    + apiKey (string, `b55bbec8-81d3-4ba5-8626-c1c7568a8106`) 
        The Darwin API key
    + rows (int, optional) 
        The number of rows to return (up to 150)
        + Default: 10
        

### /train/EUS/to [GET]

+ Response 200 (application/json)

        [
            {
                "destinations": [
                    {
                        "stationCode": "NMP", 
                        "stationName": "Northampton"
                    }
                ], 
                "estimatedArrivalTime": null, 
                "estimatedDepartureTime": "On time", 
                "operatorCode": "LM", 
                "operatorName": "London Midland", 
                "origins": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "platform": null, 
                "scheduledArrivalTime": null, 
                "scheduledDepartureTime": "00:34", 
                "serviceId": "gexsoLcgThseYrxL8G2tPg=="
            }, 
            {
                "destinations": [
                    {
                        "stationCode": "MKC", 
                        "stationName": "Milton Keynes Central"
                    }
                ], 
                "estimatedArrivalTime": null, 
                "estimatedDepartureTime": "On time", 
                "operatorCode": "LM", 
                "operatorName": "London Midland", 
                "origins": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "platform": null, 
                "scheduledArrivalTime": null, 
                "scheduledDepartureTime": "01:34", 
                "serviceId": "ZcFeH25ZaATsfN2IRlcXzg=="
            }
        ]


## ./train/{station}/from [/api/train/{station}/from?apiKey={apiKey}&rows={rows}]
Retreive all departures for the station given, which can be either a station code, or a station name.

+ Parameters
    + station (string, `London Euston`)  
        The name or code for the station
    + apiKey (string, `b55bbec8-81d3-4ba5-8626-c1c7568a8106`) 
        The Darwin API key
    + rows (int, optional) 
        The number of rows to return (up to 150)
        + Default: 10
    

### /train/London Euston/FROM [GET]

+ Response 200 (application/json)

        [
            {
                "destinations": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "estimatedArrivalTime": "00:32", 
                "estimatedDepartureTime": null, 
                "operatorCode": "VT", 
                "operatorName": "Virgin Trains", 
                "origins": [
                    {
                        "stationCode": "WVH", 
                        "stationName": "Wolverhampton"
                    }
                ], 
                "platform": "5", 
                "scheduledArrivalTime": "00:06", 
                "scheduledDepartureTime": null, 
                "serviceId": "HudMqaloWGHXlG9oTES/Hw=="
            }, 
            {
                "destinations": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "estimatedArrivalTime": "00:29", 
                "estimatedDepartureTime": null, 
                "operatorCode": "LM", 
                "operatorName": "London Midland", 
                "origins": [
                    {
                        "stationCode": "BHM", 
                        "stationName": "Birmingham New Street"
                    }
                ], 
                "platform": "8", 
                "scheduledArrivalTime": "00:21", 
                "scheduledDepartureTime": null, 
                "serviceId": "OaQLS1Fd0zzGKRrAkDb4/Q=="
            }
        ]    


## ./train/{station}/from/{station2} [/api/train/{station}/from/{station2}?apiKey={apiKey}&rows={rows}]
Retreive all departures for the station given, which can be either a station code, or a station name.

+ Parameters
    + station (string, `London Euston`)  
        The name or code for the station
    + apiKey (string, `b55bbec8-81d3-4ba5-8626-c1c7568a8106`) 
        The Darwin API key
    + rows (int, optional) 
        The number of rows to return (up to 150)
        + Default: 10
    + station2 (string, optional, `Wvh`)
        The seconday station to filter results with
    

### /train/London Euston/FROM/Wvh [GET]

+ Response 200 (application/json)

        [
            {
                "destinations": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "estimatedArrivalTime": "00:33", 
                "estimatedDepartureTime": null, 
                "operatorCode": "VT", 
                "operatorName": "Virgin Trains", 
                "origins": [
                    {
                        "stationCode": "WVH", 
                        "stationName": "Wolverhampton"
                    }
                ], 
                "platform": "5", 
                "scheduledArrivalTime": "00:06", 
                "scheduledDepartureTime": null, 
                "serviceId": "HudMqaloWGHXlG9oTES/Hw=="
            }, 
            {
                "destinations": [
                    {
                        "stationCode": "EUS", 
                        "stationName": "London Euston"
                    }
                ], 
                "estimatedArrivalTime": "On time", 
                "estimatedDepartureTime": null, 
                "operatorCode": "VT", 
                "operatorName": "Virgin Trains", 
                "origins": [
                    {
                        "stationCode": "WVH", 
                        "stationName": "Wolverhampton"
                    }
                ], 
                "platform": null, 
                "scheduledArrivalTime": "01:15", 
                "scheduledDepartureTime": null, 
                "serviceId": "1PbEDM7OTrqy6VEUqRbxjQ=="
            }
        ]


# Group ./service

## ./service [/api/service?id={id}&apiKey={apiKey}]
Retreive all departures for the station given, which can be either a station code, or a station name.

+ Parameters
    + id (string, `lvTZD/b7EAPeSnfjvD6DNA==`)
        A base64 string that represents the service id
    + apiKey (string, `b55bbec8-81d3-4ba5-8626-c1c7568a8106`) 
        The Darwin API key
    

### /service?id=1PbEDM7OTrqy6VEUqRbxjQ [GET]
